### ISSUE TITLE
Incompatible types when using @graphql-codegen/cli

### ISSUE THREAD

**Issue by alx13** [Urigo/graphql-modules#420]
I was trying to create new project with TypeScript using this instruction: https://graphql-modules.com/docs/recipes/graphql-code-generator
But I'm getting error about incompatible types when compiling using tsc:
```
[ERROR] 23:09:05 ⨯ Unable to compile TypeScript:
src/modules/index.ts:19:44 - error TS2345: Argument of type '{ typeDefs: any; resolvers: { Query: QueryResolvers<ModuleContext<{ [key: string]: any; }>, Query>; }; }' is not assignable to parameter of type 'GraphQLModuleOptions<any, any, { [key: string]: any; }>'.
  Types of property 'resolvers' are incompatible.
    Type '{ Query: QueryResolvers<ModuleContext<{ [key: string]: any; }>, Query>; }' is not assignable to type 'IResolvers<any, ModuleContext<{ [key: string]: any; }>> | IResolvers<any, ModuleContext<{ [key: string]: any; }>>[] | Promise<IResolvers<any, ModuleContext<{ [key: string]: any; }>> | IResolvers<any, ModuleContext<{ [key: string]: any; }>>[]> | ((module: GraphQLModule<any, any, { [key: string]: any; }>, ...args: any[]) => MaybePromise<IResolvers<any, ModuleContext<{ [key: string]: any; }>> | IResolvers<any, ModuleContext<{ [key: string]: any; }>>[]>) | undefined'.
      Type '{ Query: QueryResolvers<ModuleContext<{ [key: string]: any; }>, Query>; }' is not assignable to type 'undefined'.

 19 export const AppModule = new GraphQLModule({
                                               ~
 20   typeDefs,
    ~~~~~~~~~~~
...
 23   },
    ~~~~
 24 });
    ~
```

`src/modules/index.ts`
```typescript
import gql from 'graphql-tag';
import { GraphQLModule } from '@graphql-modules/core';
import { QueryResolvers } from '../generated-models';


const Query: QueryResolvers = {
  myData() {
    return true;
  },
};

const typeDefs = gql`
    type Query {
        myData: Boolean!
    }
`;

export const AppModule = new GraphQLModule({
  typeDefs,
  resolvers: {
    Query,
  },
});
```
`codegen.yml`
```yaml
overwrite: true
schema: ./src/schema.ts
require:
  - ts-node/register/transpile-only
generates:
  ./src/generated-models.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      contextType: '@graphql-modules/core#ModuleContext'
```

versions:
```yaml
dependencies:
  '@graphql-modules/core': 0.7.0
  '@graphql-modules/di': 0.7.0
  '@graphql-modules/epoxy': 0.4.0
  '@graphql-modules/sonar': 0.4.0
  apollo-server: 2.4.8
  graphql: 14.2.1
  graphql-tag: 2.10.1
  reflect-metadata: 0.1.13
  ts-utils: 6.0.7
  tslib: 1.9.3
devDependencies:
  '@graphql-codegen/cli': 1.0.7
  '@graphql-codegen/typescript': 1.0.7
  '@graphql-codegen/typescript-resolvers': 1.0.7
  '@types/graphql': 14.2.0
  '@types/node': 10.14.4
  ts-node: 8.0.3
  ts-node-dev: 1.0.0-pre.32
  tslint: 5.15.0
  typescript: 3.4.3
```

**Comment by alx13** [comment]
For now I fixed it using `Required` and `Pick` type on `QueryResolvers`:
```typescript
import { gql } from 'apollo-server';
import { GraphQLModule } from '@graphql-modules/core';
import { QueryResolvers } from '../generated-models';


const typeDefs = gql`
  type Query {
      myData: Boolean!
  }
`;

const Query: Required<Pick<QueryResolvers, | 'myData' >> = {
  myData() { return true; },
};

export const AppModule = new GraphQLModule({
  typeDefs,
  resolvers: {
    Query,
  },
});
```

**Comment by alx13** [comment]
Actually it's related to dotansimha/graphql-code-generator#1133
So may be just mention in docs that `useIndexSignature: true` should be included in `codegen.yml`:

```yaml
overwrite: true
schema: ./src/schema.ts # You can use .js files as well
require:
  - ts-node/register/transpile-only # required if you're using TS-Node
generates:
  ./src/generated-models.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      contextType: @graphql-modules/core#ModuleContext
      useIndexSignature: true
```
